/// Flutter icons LightsOnIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LightsOnIcons
///      fonts:
///       - asset: fonts/LightsOnIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class LightsOnIcons {
  LightsOnIcons._();

  static const _kFontFam = 'LightsOnIcons';
  static const _kFontPkg = null;

  static const IconData ic_fluent_lightbulb_24_regular = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_fluent_lightbulb_24_filled = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
